### ISSUE TITLE
Unstrict config keys in tailwind.config.js and figcaption.js

### ISSUE THREAD

**Issue by dsturm** [kellymears/tailwind-gutenberg-components#3]
In https://github.com/kellymears/tailwind-gutenberg-components/blob/9d170fd66a6d477f99d4eff7379d313332a0b85c/tailwind.config.js#L119-L129 config for figCaption is referenced as a subset of 'images' where as in https://github.com/kellymears/tailwind-gutenberg-components/blob/9d170fd66a6d477f99d4eff7379d313332a0b85c/src/figcaption.js#L5 it is its own.

Which key should be used? Should a (sub-)module check, wether config is set or is set to `false` and break if not?

**Comment by kellymears** [comment]
What would be your recommendation, @dsturm? I felt unsure about more than a few of the pairings.

**Comment by dsturm** [comment]
I'm not quite sure, since figure captions are generally bound to images. But since [it's valid to use other tags, like `<pre>` or `blockquote`,  without `<img>` in `<figure>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figure) I tend towards its own key and not as a subset.

**Comment by kellymears** [comment]
@dsturm fixed this while writing some new modules (and updating old stuff).

thanks!
