### ISSUE TITLE
Add as a block to WP itself

### ISSUE THREAD

**Issue by 7Ds7** [kellymears/tailwind-gutenberg-components#4]
I am a little confused here, and sorry if this is not the right place to ask.

I have created blocks with https://github.com/ahmadawais/create-guten-block and added them to my theme/plugin although in this repo i only see javascript files and am kind of lost on how to include it on my theme/plugin etc...

Any hints on how to do it?

**Comment by kellymears** [comment]
Hey @7ds7 you should check out [the tailwind documentation](https://tailwindcss.com/docs/).

Most germane to using this repo would be [the section on plugins](https://tailwindcss.com/docs/configuration/#app).

Good luck!
